### ISSUE TITLE
Feature Request: add support for the Aerosoft A320 series

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#106]
One for the future but shall add it here for reference. Initial ideas included using a .net OCR engine to read the CDU's. Access to panels is there and the MCP panel would be the minimum initially to make the aircraft flyable I would say. Link to a video of FSFO support below, attached are some initial notes I made from research as well. I do have the aircraft so ask if any help in the initial phases needed.  
https://www.youtube.com/watch?v=ANCGpgvlEN4&t=983s
[Aerosoft airbus's notes.txt](https://github.com/jfayre/talking-flight-monitor-net/files/6954491/Aerosoft.airbus.s.notes.txt)

**Comment by ajborka** [comment]
Recent developments found a better alternative for a A320 and A388 when it is released by Fly by wire. We won't be working on Aerosoft.
