### ISSUE TITLE
bug:  on descent when engine is at idal, the throttle percentage value is negative.

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#117]
Sorry about any misspellings. I'm writing this on iOS.

**Describe the bug**
I was descending into KMCI and using the PMDG 737-8 converted frater and looked at my throttle percentage. I was at idol during most of the descent.

**To Reproduce**
1. Start a descent.
2. Make sure the engine is at idol.
3. Hit TFM plus control number row  1. 

**Expected behavior**

I expect that percentage to  be positive, or 0?

**additional information
 - windows 10 64 bit 2021 build OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use:  prepar 3D v4.5
- specific aircraft in use: PMDG 737-8 converted frator.

**Additional context**
Video is here.

https://www.dropbox.com/s/ig0vmj5hakcfzgd/engine%20thrust%20negative.MP4?dl=1

**Comment by ajborka** [comment]
Will look into it.

**Comment by marrie** [comment]
Thanks. I cannot test with other planes at this time. I also I think forgot to add I'm using TFM ending in 18.2. or what ever is latest on the snaps page.

**Comment by ajborka** [comment]
This can't be verified in recent builds of TFM.
