### ISSUE TITLE
PMDG bug: sometimes typing values into mcp boxes does not remove prior value

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#119]
experienced this mainly with the heading and speed fields. Tested in the 737 p3dv4. Most of the time, expected behaviour occurs and the prior value is removed and new value entered. However, sometimes it is not, resulting in the two values being in the box together, I.E heading 2320, and the mcp just defaults the value to 0.

**Comment by ajborka** [comment]
I have seen this problem sometimes. Will look into it for the 18.4 build.

**Comment by ajborka** [comment]
Fixed in the 22 cycle.
