### ISSUE TITLE
PMDG747: distance to destination and ETA don't update unless you restart TFM

### ISSUE THREAD

**Issue by MixingTech** [talking-flight-monitor/talking-flight-monitor#121]
simple to re-produce, running TFM18.2 in PMDG 747 - 400 and 8 series all have the same issue, once airborn distance to destination does not read until you restart TFM then once restarted off the ground distance to destination will read. however the ETA does not update depending on your speed forcing you to restart again once at final altitude and speed

**Comment by ajborka** [comment]
Fixed in preview 23.1.
