### ISSUE TITLE
Suggestion: have steps speak if possible when aligning IRS

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#123]
I'm using for now the PMDG 737NGXU model. I've taken to aligning  the IRS myself as I'm testing something. I noticed though and I know you guys are aware, that the steps don't speak. So I literally have to if I wanted to, pull out my stopwatch and wait  30 seconds, or if I wanted to, for 10 or so minutes it takes to align that. Is there going to be a way for talking flight monitor to speak the steps as this is happening? That is, are there lights that turn on and off as the steps are being executed after you copy GPS left into 4 right on the previous page? I'm not going to put this as a bug, as it really isn't. At least, I don't think so.

**Comment by ajborka** [comment]
This will most likely happen after the 737 rewrite.

**Comment by marrie** [comment]
Cool. I forgot I made that suggestion. Lol! Can’t wait.  Thanks.

**Comment by ajborka** [comment]
Tis is fixed after the PMDG 737 rewrite. You can tell when the IRU is requesting input into the FMC by the left and right IRU lights constantly blinking.
