### ISSUE TITLE
suggestion: have a hotkey to disconnect from the simulator

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#124]
# use case

If I'm going to be doing other things during a flight and let's say I'm on time compression, I don't want to hear any output such as sim rate, , alt, etc hence why I would want to disconnect tfm from the sim. If this is implemented though a reminder every x minutes set up in user prefs could be a good way to know why tfm is not working. This could be a different key than the reconnect which we already have. Right now I just shut down tfm, but this is not the ideal solution

**Comment by ajborka** [comment]
This is fixed with the more recent preview 23.1 by adding a mute TFM command.
