### ISSUE TITLE
aircraft dialogue suggestions and bugs 

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#137]
These are interlinked bugs or requests with the aircraft dialogue:
On vatsim the listed speed appears to jump around improbably, sometimes by 100 kts, for the other aircraft, within a short space of time. Having crosschecked this with others their speed does not seem to match what TFM is listing. This could be a vatsim reporting problem not sure.
Secondly adding a shift p key to just pull the nearest aircraft so that the entire dialogue, sometimes with many aircraft, does not load and lag NVDA during critical stages of flight. Shift P would just read the closest aircraft through NVDA automatically.

**Comment by ajborka** [comment]
Most of this is fixed. The lag behind or speeds jumping all over is a simulator problem that TFM can't fix.
