### ISSUE TITLE
bug:  transponder must be entered twice  to register in the pmdg 737 series

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#140]
**Describe the bug**

when I enter the transponder of let's say 1457 or what ever vatsim gives me I have to enter it twice. This happened 2 weeks ago while on flight and I didn't notice until they asked me to confirm  I had my transponder  set to what ever they gave me. I have been testing off line, and I indeed have to enter it twice. After that I'm fine if I have to reset it to something else

**To Reproduce**
1. launch prepar3d
2. choose the pmdg 737-8 (testing will have to be done in the 777 to make sure this issue did not carry over)
3. launch tfm
4. launch fsfo to help with set up
5. hit AP then shift t.
6. enter 4 numbers such as 1460
7. hit enter
8. repeat steps 6 and 7
You will then hear the confirmation  the transponder has been set.
**Expected behavior**
I expected to only have to do this once. I'm not sure when it broke  so cannot regress as I just noticed it.
**additional information
 - OS: [e.g. Windows 10] Windows 10 21H2 (x64) build 19044.1645
 - TFM version: Version 22.1.0.0
 - Flight simulator in use:  prepared version 4.5
- specific aircraft in use: pmdg 737-8 in house (not converted frater (although I can confirm this happens with the cf model as well)
**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
n/a

**Comment by trodick** [comment]
As a workaround until this is fixed, use the dot command in VPilot. .xpdr nnnn, where nnnn is the requested squawk code. -Ty

**Comment by BviPilots** [comment]
Sorry, but what is this bug again? I only got part of this message and was wanting to see what it was beings all I fly is the b737.
Thanks,

**Comment by ajborka** [comment]
Are you starting the 738 from cold/dark? If so, you will need to start from long or short panel stats until we get the transponder and comm panels done. First officer doesn't turn on comms or transponders in the 73x airplanes. It will probably work in the 77x series because FSO turns on the transponder. You will need to enter the comms/transponder condes in the fcomms page of the 77x airplanes.

**Comment by marrie** [comment]
If you read the bug basically you have to enter the transponder twice if
you are hitting SP then shift t. I don't use .x if I'm in VPilot, in fact I
forgot about that. Try that work around I guess.

**Comment by marrie** [comment]
I am starting from long turn around  state. Should I try starting from cld the next time I fly? I have not tested in the 777 as of yet.

**Comment by ajborka** [comment]
Try from the short turnaround state. If that doesn't work, try from the default startup state.

**Comment by marrie** [comment]
Looks like the cld state worked, and No I don't mean clearance and delivery
this time lol! I'm flying offline and was able to reset my transponder
only once, not twice this time.  I'll keep an eye on this over the next few
weeks.

**Comment by marrie** [comment]
That will work, if I’m flying online, but if I’m flying with atc programs that will not work, I don’t think? Feel free to correct me if I’m wrong.

TY

**Comment by ajborka** [comment]
Fixed in 23.1 since the entire 737 was rewritten.
