### ISSUE TITLE
bug:  tfm appears to crash when loading the destination airport

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#141]
**Describe the bug**
when I hit tfm plus control D I get the continue dialogue when I hit enter on the airport, in my case it was cyxx

**To Reproduce**
1. launch tfm
2. go into dest mode with tfm plus control d
enter the icao cyxx

you will hear runways then the details and continue dialogue will appear. 

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Object reference not set to an instance of an object.

**Expected behavior**
the dialogue should not in theory cause tFM to crash

**additional information
 - OS: [e.g. Windows 10]Windows 10 21H2 (x64) build 19044.1645
 - TFM version: Version 22.5.0.0j
 - Flight simulator in use: prepared version 4.5
- specific aircraft in use:pmdg 737-8 in house (no bcf model)

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
the dialogue will come back after hitting continue, so the program appears to be stuck in some kind of loop, or something.

**Comment by trodick** [comment]
@marrie, please hit Details, then down arrow in the dialog until you enter the read-only edit box. Then copy/paste the contents of that edit box into this bug report, as this will tell us where in the code the problem exists.

**Comment by ajborka** [comment]
I need to see if the database has time to load the airport/runways in question. It also happens with cyeg and runway 20.

**Comment by ajborka** [comment]
I took a look at the problem. Some runways don't have an ILS system. That window doesn't check to see if there isn't an ILS. Most likely CYXX/07 isn't an ILS runway. Will put it in the priority list of things to get done.

**Comment by marrie** [comment]
Well, I did not do this while in the air, someone did reproduce this while on the ground, so here is the trace from there. Sorry about that.  I was flying with a sterile deck when I received the email. Here is the log.

See the end of this message for details on invoking 

just-in-time (JIT) debugging instead of this dialog box.

 

************** Exception Text **************

System.NullReferenceException: Object reference not set to an instance of an object.

   at tfm.DestinationForm.runwayComboBox_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\talking-flight-monitor\source\Flight planning\DestinationForm.cs:line 87

   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)

   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)

   at tfm.DestinationForm.airportTextBox_KeyDown(Object sender, KeyEventArgs e) in C:\projects\talking-flight-monitor\source\Flight planning\DestinationForm.cs:line 52

   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)

   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)

   at System.Windows.Forms.Control.WmKeyChar(Message& m)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.TextBox.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 

 

************** Loaded Assemblies **************

mscorlib

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

----------------------------------------

tfm

    Assembly Version: 22.5.0.0

    Win32 Version: 22.5.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/tfm.exe

----------------------------------------

System.Windows.Forms

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

----------------------------------------

System

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------

System.Drawing

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

----------------------------------------

NLog

    Assembly Version: 4.0.0.0

    Win32 Version: 4.7.10.13013

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NLog.DLL

----------------------------------------

System.Configuration

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

----------------------------------------

System.Core

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

----------------------------------------

System.Xml

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

----------------------------------------

System.Data

   Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

----------------------------------------

System.ServiceModel

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll

----------------------------------------

System.Runtime.Serialization

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

----------------------------------------

TolkDotNet

    Assembly Version: 0.0.0.0

    Win32 Version: 1.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/TolkDotNet.DLL

----------------------------------------

System.Speech

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll

----------------------------------------

fsuipcClient

    Assembly Version: 3.2.10.379

    Win32 Version: 3.2.10.379

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/fsuipcClient.DLL

----------------------------------------

NGeoNames

    Assembly Version: 1.5.1.0

    Win32 Version: 1.5.1.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NGeoNames.DLL

----------------------------------------

NHotkey.WindowsForms

    Assembly Version: 2.0.0.0

    Win32 Version: 2.1.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NHotkey.WindowsForms.DLL

----------------------------------------

NHotkey

    Assembly Version: 2.0.0.0

    Win32 Version: 2.1.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NHotkey.DLL

----------------------------------------

KdTreeLib

    Assembly Version: 1.4.1.0

    Win32 Version: 1.4.1.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/KdTreeLib.DLL

----------------------------------------

NAudio.WinMM

    Assembly Version: 2.0.0.0

    Win32 Version: 2.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NAudio.WinMM.DLL

----------------------------------------

netstandard

    Assembly Version: 2.0.0.0

    Win32 Version: 4.8.4084.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll

----------------------------------------

NAudio.Core

    Assembly Version: 2.0.0.0

    Win32 Version: 2.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NAudio.Core.DLL

----------------------------------------

Accessibility

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

----------------------------------------

 

************** JIT Debugging **************

To enable just-in-time (JIT) debugging, the .config file for this

application or computer (machine.config) must have the

jitDebugging value set in the system.windows.forms section.

The application must also be compiled with debugging

enabled.

 

For example:

 

<configuration>

    <system.windows.forms jitDebugging="true" />

</configuration>

 

When JIT debugging is enabled, any unhandled exception

will be sent to the JIT debugger registered on the computer

rather than be handled by this dialog box.

**Comment by marrie** [comment]
Actually, 7 does have an ILS. I landed on it. 

07

Heading

85°

Length

9597ft

Width

200ft

Slope

0.281°

ILS Cat I

109.7/IXX/69°

Glideslope

3.00°

**Comment by ajborka** [comment]
Another runway at that airport probably runs without one. Will fix it in the next release.

**Comment by ajborka** [comment]
The database doesn't give any indications of an RNAV or other approaches. The only one is an ILS. Sayint that, I am going to check for the ILS condition and make a not of it in the runways list.

**Comment by marrie** [comment]
I did get this to crash when trying to change the runway.  Basically I am heading toward my initial approach  fix at cyhm and got the same trace error I think. Here it is again just in case it Is not.

 

See the end of this message for details on invoking 

just-in-time (JIT) debugging instead of this dialog box.

 

************** Exception Text **************

System.NullReferenceException: Object reference not set to an instance of an object.

   at tfm.DestinationForm.runwayComboBox_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\talking-flight-monitor\source\Flight planning\DestinationForm.cs:line 94

   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)

   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)

   at System.Windows.Forms.ComboBox.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 

 

************** Loaded Assemblies **************

mscorlib

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4510.0 built by: NET48REL1LAST_B

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

----------------------------------------

tfm

    Assembly Version: 22.5.0.0

    Win32 Version: 22.5.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/tfm.exe

----------------------------------------

System.Windows.Forms

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

----------------------------------------

System

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------

System.Drawing

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

----------------------------------------

NLog

    Assembly Version: 4.0.0.0

    Win32 Version: 4.7.10.13013

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NLog.DLL

----------------------------------------

System.Configuration

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

----------------------------------------

System.Core

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

----------------------------------------

System.Xml

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

----------------------------------------

System.Data

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

----------------------------------------

System.ServiceModel

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll

----------------------------------------

System.Runtime.Serialization

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

----------------------------------------

TolkDotNet

    Assembly Version: 0.0.0.0

    Win32 Version: 1.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/TolkDotNet.DLL

----------------------------------------

System.Speech

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll

----------------------------------------

fsuipcClient

    Assembly Version: 3.2.10.379

    Win32 Version: 3.2.10.379

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/fsuipcClient.DLL

----------------------------------------

NGeoNames

    Assembly Version: 1.5.1.0

    Win32 Version: 1.5.1.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NGeoNames.DLL

----------------------------------------

NHotkey.WindowsForms

    Assembly Version: 2.0.0.0

    Win32 Version: 2.1.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NHotkey.WindowsForms.DLL

----------------------------------------

NHotkey

    Assembly Version: 2.0.0.0

    Win32 Version: 2.1.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NHotkey.DLL

----------------------------------------

KdTreeLib

    Assembly Version: 1.4.1.0

    Win32 Version: 1.4.1.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/KdTreeLib.DLL

----------------------------------------

NAudio.WinMM

    Assembly Version: 2.0.0.0

    Win32 Version: 2.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NAudio.WinMM.DLL

----------------------------------------

netstandard

    Assembly Version: 2.0.0.0

    Win32 Version: 4.8.4084.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll

----------------------------------------

NAudio.Core

    Assembly Version: 2.0.0.0

    Win32 Version: 2.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NAudio.Core.DLL

----------------------------------------

Accessibility

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

----------------------------------------

System.Xml.Linq

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

   CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

----------------------------------------

TimeZoneConverter

    Assembly Version: 3.5.0.0

    Win32 Version: 3.5.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/TimeZoneConverter.DLL

----------------------------------------

 

************** JIT Debugging **************

To enable just-in-time (JIT) debugging, the .config file for this

application or computer (machine.config) must have the

jitDebugging value set in the system.windows.forms section.

The application must also be compiled with debugging

enabled.

 

For example:

 

<configuration>

    <system.windows.forms jitDebugging="true" />

</configuration>

 

When JIT debugging is enabled, any unhandled exception

will be sent to the JIT debugger registered on the computer

rather than be handled by this dialog box.

**Comment by ajborka** [comment]
Try it with 22.5.1. It works fine for me. It gives me runways 12 and 30.

**Comment by marrie** [comment]
Ok, I see the 2 runways at first, then when I go back into the destination dialogue to change runways let’s say, then the crash appears per the log I sent last night.  So I let’s say choose 12, vatsim changes it to 30. I go into the destination and choose 30, and only then do I see the continue, details and quit buttons

**Comment by marrie** [comment]
Ok, so in cyhm, the only ils according to pmdg is ils runway 12. 30 is a loc approach; yet with stkp I show an ILS for 30, so now I’m a bit confused. I’m not sure which is true, and now I know why I think I might be having trouble, maybe. I’ll know when I get there in about 3 hours. Can anyone else confirm that at least in the case of CYHM I only see ils runway 12 and not ils runway 30? If tfm is treating the loc as an ILS this might or might not explain a lot. 

 

Thanks.

**Comment by ajborka** [comment]
CYHM has two runways: ILS12 and LOC30. In the destination runway window, selecting runway 30 will give clues as to the runway type. In the ILS details field, runway 30 has these values:

name: LOC 30
slope: 0

Since there isn't a glide slope, the slope value is 0. The full name also has LOC before the runway name. In the case of runway 12:

name: ILS 12...
slope: 3

This is an ILS with glide slope because the full name has ILS before it. The slope is 3 degrees, so we know it has a glide slope attached. Future updates will fix this problem.

**Comment by marrie** [comment]
Yep, that matches up  to what I see  in stkp. I get to try the loc apr again.  Here is what I see in stkp.

Heading

287°

Length

10006ft

Width

197ft

Slope

0.100°

Localizer Only

110.9/IER/297°

Glideslope

NaN°

 

It also looks like  they line up with VORs or something as you can see with runway 12 as well as runway 30. 

 

Heading

107°

Length

10006ft

Width

197ft

Slope

-0.100°

ILS Cat II

110.9/IAB/117°

Glideslope

3.00°

 

I happen to pick a very complex airport to test with. Lol!

**Comment by marrie** [comment]
When attempting to change  ILS runways, let's say if vatsim makes a mistake (this already happened) or if I do (this already happened) the loop will resume.  I can change runways, however the continue dialogue wiht the details and continue button will get in the way while I do this, causing the end user to have to keep clicking "continue"

**Comment by ajborka** [comment]
I need the following information before trying this.

* The text of the details window when it crashes.
* TFM's logfile at <TFM install folder>/tfm.txt.
* The airport you tried to change runways at.
* The runways you tried to change from/to.
* Give a step by step list of directions on how to reproduce the problem.
* Did you turn on/off app mode when changing runways?

**Comment by marrie** [comment]
I actually  did see 12 and 30, but when I went to change the runway from 12 to 30, I got the error. I will be trying that flight again as i ran into a snag when landing. We'll see if I can reproduce the crash.
