### ISSUE TITLE
Bug: auto throttle key gets intercepted when you mute sim messages

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#142]
**Describe the bug**
when you hit shift r while in the sim after hitting TFM (that is, right bracket) auto throttle is turned on or off

**To Reproduce**
1. launch prepared
2. launch tfm
3. get into the 737-800
4. stay in the sim window and hit tfm plus shift r. Now try that outside the sim window, for example on the  desktop. When outside the sim window the muting of sim messages works correctly.

**Expected behavior**
I should not have that key intercepted by the sim.

**additional information
 - OS: [e.g. Windows 10]Windows 10 21H2 (x64) build 19044.1706
 - TFM version: v2.5.1
 - Flight simulator in use: p3dv4.5
- specific aircraft in use:pmdg737-800

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
n/a

**Comment by ajborka** [comment]
What livery are you using. The default PMDG ones never had this problem. American, United, and Southern cargo are the ones we know about so far.

**Comment by ajborka** [comment]
I tried it in all variants from 737 series and got the same result. It is most likely a key conflict between TFM and PMDG. At this point, the only way to fix it is to change your AT engage shortcut to something else.

**Comment by ajborka** [comment]
No reports of this happening in over 6 months, so closing.
