### ISSUE TITLE
Feature request: reposition to taxiways 

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#152]
Similar concept to gates and runways, but in this case all named taxiways TFM can pull are listed and you can jump to them. Examples of TFM pulling such taxiways can be seen with shift C when pushing back or when short of the runway. 
Useful in cases where vatsim controllers cannot position you straight onto the runway but want you to reposition to a taxiway close to the runway to join the cue. Sometimes they are more willing to do this progressive form of movement rather than a straight position onto the runway.
Note some sceneries are more detailed than others with labelling. Some have runway holding points labelled, some have only a few taxiways and some small airports may have none labelled, so very experimental.
Hopefully this is data TFM can get access to, seems like it since it works with shift C to read taxiways but unsure about repositioning to them.

**Comment by ajborka** [comment]
Will look into it.

**Comment by ajborka** [comment]
This is not possible at this time.
