### ISSUE TITLE
bug: Using VATSIM gives an error and nothing appears

### ISSUE THREAD

**Issue by FlyingBlind-pt** [talking-flight-monitor/talking-flight-monitor#153]
When activating Using Vatsim on the Settings in Preview 22.11, it gives an error "Cannot unmarshall Type ServerEnum". I press Continue and it gives nothing as output. Tried restarting TFM, having no CDU or anything else TFM-related open, to no avail.
Using P3dV4.5, VPilot is connected, Windows 10 language Portuguese from Portugal, latest updates, latest NVDA. At the same time, FSAirlines Client, SimToolKit Pro, FSFO Pro, PMDG 737-700 at the moment. Thanks and great job!

**Comment by ajborka** [comment]
We will look at it later. The suspected problem is that we aren't given enough time to download the entire dataset.

**Comment by ajborka** [comment]
There isn't anything we can do for this at the time. It appears the Vatsim pilots API result set is too large to process before the server recycles the request again. When there is another more reliable way to do this, we will look into it.
