### ISSUE TITLE
left bracket MCP boxes no longer report current mode

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#158]
Hi, using preview 22  11.2, the current autopilot mode is not read when you use left bracket followed by, for example, A or H. Previous versions would say, again for example, mcp altitude 33000, VNAV. Currently left bracket A just reads as 33000. Same thing with heading modes, airspeed modes ETC. Thanks

**Comment by ajborka** [comment]
Will look into why this happens.

**Comment by ajborka** [comment]
Fixed in upcoming 23.2 preview.
