### ISSUE TITLE
TFM brings up the dialog offering to quit or continue when rebuilding  the database

### ISSUE THREAD

**Issue by Glenn1212** [talking-flight-monitor/talking-flight-monitor#161]
If you go in to settings and set your TFM database,  for MSFS, and you hit the keystroke  to rebuild it, TFM will throw up an error dialog offering to quit or continue.
[tfm.log](https://github.com/talking-flight-monitor/talking-flight-monitor/files/10421795/tfm.log)

**Comment by ajborka** [comment]
Did you start MSFS and put yourself into an airplane first?

**Comment by ajborka** [comment]
Fixed in the upcoming preview.
