### ISSUE TITLE
TFM throws several hotkey errors no matter what sim or aircraft I'm in

### ISSUE THREAD

**Issue by tylerchambliss** [talking-flight-monitor/talking-flight-monitor#163]
TFM throws several hotkey errors. It happens every time I press the TFM command key. Here's a recording of what happens. https://www.dropbox.com/s/176u2rz6jylpubq/2023-01-30_15-36-38.mp3?dl=1
 And a link to my TFM log file.
https://www.dropbox.com/s/iutxtnymplvns1y/tfm.log?dl=1

**Comment by ajborka** [comment]
Make sure other addons don't have the same hotkeys that TFM uses. Looks like there is an addon using the same nHotkey library we use and attempting to use the same key definitions we use.

**Comment by jfayre** [comment]
Since we register global hot keys in windows, the problem could actually be anything that registers a global hotkey. Not necessarily just a flight simulator add-on.Sent from my iPhoneOn Jan 30, 2023, at 5:32 PM, Andy Borka ***@***.***> wrote:﻿
Make sure other addons don't have the same hotkeys that TFM uses. Looks like there is an addon using the same nHotkey library we use and attempting to use the same key definitions we use.

**Comment by tylerchambliss** [comment]
The only things I had running were the sim, TFM, NVDA, and my virtual
airline's ACARS which I  know wouldn't be messing with anything.

**Comment by jfayre** [comment]
Have you tried deleting your Settings file? Under application data.Sent from my iPhoneOn Jan 30, 2023, at 6:57 PM, tylerchambliss ***@***.***> wrote:﻿
The only things I had running were the sim, TFM, NVDA, and my virtual
airline's ACARS which I  know wouldn't be messing with anything.

**Comment by tylerchambliss** [comment]
Yes, I have as well as re-installing the sim, and nothing seems to fix it.

**Comment by tylerchambliss** [comment]
I meant re-installing TFM, not the sim.

**Comment by ajborka** [comment]
TFM isn't the cause of this problem. Some other application is assigning keyboard commands that conflict with TFM. Remove or reassign the other application's keyboard commands to resolve the problem.

**Comment by tylerchambliss** [comment]
Well I don't have any other apps that  would be doing that, and the issue
has seemed to fix it's self.
