### ISSUE TITLE
Bug: Connection fails when connecting to MSFS and PMDG 737

### ISSUE THREAD

**Issue by ricki32** [talking-flight-monitor/talking-flight-monitor#174]
Upon starting TFM after about 2 minutes it right away states connection lost please see TFM log and restart TFM. I restart to no avail or success. I also adjust my flaps and hit ]l and it just says flaps 0 even though they are at 5. That is what is going on so far and I have uninstaleed the program twice to no avail.
[tfm.log](https://github.com/talking-flight-monitor/talking-flight-monitor/files/12901434/tfm.log)

**Comment by ajborka** [comment]
You most likely need to add the [SDK] section to the options.ini file for the PMDG 737. www.bvipilots.net has an options.ini file with the required section already added. The FSUIPC documentation also describes how to add this section. This is not a TFM problem and a design set by PMDG.
