### ISSUE TITLE
command key followed by D fails to report anything after time on route to except the time.

### ISSUE THREAD

**Issue by stickbear2015** [talking-flight-monitor/talking-flight-monitor#19]
when you push command key D, it says time inroute to, followed by a pause, then the time.
I think it's supposed to say time inroute to followed by your final destination, followed by the hours minutes seconds readout.
I could be totally wrong, but looking at the inflection it's reporting  it seems a bit off.

**Comment by marrie** [comment]
I can reproduce this, but this right now is not yet implemented at this point in time. To add to this, I'd love to see a way to view this in the GUI as well.

**Comment by ajborka** [comment]
This is stale and needs further/recent justification to implement for freeware aircraft. The UI in TFM is changing, so this may not be valid anymore.
