### ISSUE TITLE
suggestion: when going direct to a way point if instructed by vat sim, or if you want to do this offline, the plan should sync with where you actually are.

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#42]
# issue
When you are asked to go direct to a way point by vatsim or if you want to do this yourself, the time to dest and the next way points should reflect this.  The reason this is not being submitted as a bug as it is not one, at least as far as TFM is concerned, but in my case an FSTramp issue, where if you do go direct, your destination, and way points are screwed up. It will show the last way point you went to; basically there is no way to catch the GPS up.

# suggestion
if this should happen for what ever reason, there should be a way either via buttons inside the app or via the tfm keys (I'd prefer in app) to catch TFM up. If we can kill two birds with one stone, thereby having tfm not do what it does now and screw up when you do go direct, that would be nice.

**Comment by jfayre** [comment]
Once we have control of the flight plan, this is totally possible. 

Thanks for the suggestion.

**Comment by ajborka** [comment]
Putting it on my list of things to do.

**Comment by ajborka** [comment]
This is stale and needs further/more recent justification to implement for freeware aircraft.
