### ISSUE TITLE
Feature request: List of nearest cities with bearing.

### ISSUE THREAD

**Issue by Hadi-1624** [talking-flight-monitor/talking-flight-monitor#77]
Hi guys
IT would be awesome if there was an option that we could set a radius, e.g., 5 miles, 10 miles, 20 miles, 50 miles, then with a hotkey TFM would show us the nearest cities with their bearing.
Would have two benefits, first, you could use the list to see which cities are around you, and possible you can also figure out when you are crossing a border or flying alongside it, or even flying past  three bordering countries!
Second, you could manually fly around the places you are familiar with and have just some fun with general aviation aircraft.
TBH i'm mostly asking this feature so i can have some fun with general aviation aircraft, manually adjusting throttle and  turning the aircraft by hand, and to have some sort of purpose while doing this
Thanks for what you guys do.

**Comment by marrie** [comment]
I like the idea, I marked it as thumbs down, as that would be nice to have, but not very necessary at least not for all of us.￼

**Comment by Hadi-1624** [comment]
Could you explain why it is not necessary perhaps? I would like to know. Is it not nice to understand  where exactly you are?
You could, for example, be  flying past Paris which could be  50 miles to your west, but at the moment, you wouldn't be able to tell, unless you are well adept at the geography of your route.
Part of flight simulation is to understand where your route is going and which cities you are passing by and where your aircraft is.

**Comment by marrie** [comment]
Oh, for me I just use tfm then shift plus c to know what is below me. For me I don’t need to, or want to know what is actually around me, maybe airport wise, which we can already do, but not city wise. Plus I’m not sure Bing might be able to do that. It is not high priority, is all I’m trying to say. If you think tis, you can react with a thumbs up reaction and the more of them they have the more they will bump it to the top of the to do list.

**Comment by Orinks** [comment]
Shift C doesn't report things immediately below you, nor does C itself
report where exactly where things are either. I'd like to know about
landmarks and POIs.

**Comment by marrie** [comment]
I guess I’m one of the ones who really does not find that stuff interesting. If you want it I guess mark it with thumbs up in the reaction panel.

**Comment by ajborka** [comment]
This is stale and needs further/more recent justification to implement, especially for freeware aircraft.
