### ISSUE TITLE
Feature request: Implement fs 2020 flight plan format

### ISSUE THREAD

**Issue by ajborka** [talking-flight-monitor/talking-flight-monitor#78]
FS2020 .pln file format carries extended information about the flight plan. One of these is the ability to indicate a sid and star. The benefit is that TFM can automatically pick up on the sid/star and populate the waypoints if they aren't already included in the file. Another benefit is that requesting TFM tell you the next waypoint will include sid/star waypoints. So, it will fix the problem with TFM not reading sid/star waypoints. It seems to be an easier file format to use as an end-user as well.

**Comment by marrie** [comment]
To add to this, all way  point restrictions if any should be able to be adhered to. The user should also have the ability to override said restrictions if lying online, or whatever the situation might deem for doing this.￼￼ i'm very well aware of being redundant as I believe this was discussed before somewhere.￼

**Comment by ajborka** [comment]
This is stale and needs further/more recent justification to implement for freeware aircraft.
