### ISSUE TITLE
When a star with a manual termination is encountered, fly the same heading until user input

### ISSUE THREAD

**Issue by marrie** [talking-flight-monitor/talking-flight-monitor#79]
For some, not all arrivals, a manual termination is given before the approach waypoint. This is fine, except when the user is not aware. If this happens, the same heading as the manual termination should be flown until:

* the user inputs the heading to the waypoint as directed by vatsim, or when the user judges it appropriate if flying offline, or 
* the user right clicks the first approach waypoint and clicks "fly plan from here." Or what ever the instruction for that will be in the end.

**Comment by marrie** [comment]
I should add that this would only apply to the freeware aircraft. Probably not the payware aircraft. I'm still not sure if that's a good idea to only apply this to the freeware aircraft, should've played at all?￼

**Comment by ajborka** [comment]
This is stale and needs more recent justification to implement for freeware aircraft.
