### ISSUE TITLE
feature request: add a go around mode 

### ISSUE THREAD

**Issue by blindflightsimmer** [talking-flight-monitor/talking-flight-monitor#82]
The idea for this feature would be:
user hits a hotkey with tfm.
Approach mode is de-activated if turned on.
speed is set to 200 knots.
altitude is set to 3000 feet.
climbrate is set to 2000 feet per minute.
flaps and gear are retracted (optional since the user could do this themselves)
The user can then use tramp, or tfm in the future, to try the approach again

**Comment by jfayre** [comment]
I like it. Should be fairly easy to do.

**Comment by marrie** [comment]
should we add /3000A as I had to go around and I got asked to go up to 5000 ft. I realize i "m writing in pmdg code and not freeware code, but just some thoughts anyway in case someone is flying a freeware aircraft. Of corse the user will be able to implement a higher alt anyway if told by ATC.

**Comment by ajborka** [comment]
This is stale and needs current justification to implement for freeware aircraft.
